# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/peter/Desktop/tests/datadriven

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/peter/Desktop/tests/datadriven/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/peter/Desktop/tests/datadriven/build/CMakeFiles /home/peter/Desktop/tests/datadriven/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/peter/Desktop/tests/datadriven/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Main

# Build rule for target.
Main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Main
.PHONY : Main

# fast build rule for target.
Main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/build
.PHONY : Main/fast

#=============================================================================
# Target rules for targets named LocusMathFunctions

# Build rule for target.
LocusMathFunctions: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LocusMathFunctions
.PHONY : LocusMathFunctions

# fast build rule for target.
LocusMathFunctions/fast:
	$(MAKE) $(MAKESILENT) -f locusBase/CMakeFiles/LocusMathFunctions.dir/build.make locusBase/CMakeFiles/LocusMathFunctions.dir/build
.PHONY : LocusMathFunctions/fast

#=============================================================================
# Target rules for targets named Core

# Build rule for target.
Core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Core
.PHONY : Core

# fast build rule for target.
Core/fast:
	$(MAKE) $(MAKESILENT) -f locusBase/CMakeFiles/Core.dir/build.make locusBase/CMakeFiles/Core.dir/build
.PHONY : Core/fast

#=============================================================================
# Target rules for targets named RigidBody

# Build rule for target.
RigidBody: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RigidBody
.PHONY : RigidBody

# fast build rule for target.
RigidBody/fast:
	$(MAKE) $(MAKESILENT) -f locusBase/CMakeFiles/RigidBody.dir/build.make locusBase/CMakeFiles/RigidBody.dir/build
.PHONY : RigidBody/fast

#=============================================================================
# Target rules for targets named Forcegenerator

# Build rule for target.
Forcegenerator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Forcegenerator
.PHONY : Forcegenerator

# fast build rule for target.
Forcegenerator/fast:
	$(MAKE) $(MAKESILENT) -f locusBase/CMakeFiles/Forcegenerator.dir/build.make locusBase/CMakeFiles/Forcegenerator.dir/build
.PHONY : Forcegenerator/fast

#=============================================================================
# Target rules for targets named RigidBodyDrawer

# Build rule for target.
RigidBodyDrawer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RigidBodyDrawer
.PHONY : RigidBodyDrawer

# fast build rule for target.
RigidBodyDrawer/fast:
	$(MAKE) $(MAKESILENT) -f locusBase/CMakeFiles/RigidBodyDrawer.dir/build.make locusBase/CMakeFiles/RigidBodyDrawer.dir/build
.PHONY : RigidBodyDrawer/fast

#=============================================================================
# Target rules for targets named World

# Build rule for target.
World: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 World
.PHONY : World

# fast build rule for target.
World/fast:
	$(MAKE) $(MAKESILENT) -f locusBase/CMakeFiles/World.dir/build.make locusBase/CMakeFiles/World.dir/build
.PHONY : World/fast

#=============================================================================
# Target rules for targets named Aero

# Build rule for target.
Aero: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Aero
.PHONY : Aero

# fast build rule for target.
Aero/fast:
	$(MAKE) $(MAKESILENT) -f Entities/CMakeFiles/Aero.dir/build.make Entities/CMakeFiles/Aero.dir/build
.PHONY : Aero/fast

#=============================================================================
# Target rules for targets named rlImgui

# Build rule for target.
rlImgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rlImgui
.PHONY : rlImgui

# fast build rule for target.
rlImgui/fast:
	$(MAKE) $(MAKESILENT) -f Vendor/rlImGui/CMakeFiles/rlImgui.dir/build.make Vendor/rlImGui/CMakeFiles/rlImgui.dir/build
.PHONY : rlImgui/fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f Vendor/imgui/CMakeFiles/imgui.dir/build.make Vendor/imgui/CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

#=============================================================================
# Target rules for targets named implot

# Build rule for target.
implot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 implot
.PHONY : implot

# fast build rule for target.
implot/fast:
	$(MAKE) $(MAKESILENT) -f Vendor/implot/CMakeFiles/implot.dir/build.make Vendor/implot/CMakeFiles/implot.dir/build
.PHONY : implot/fast

main3.o: main3.cpp.o
.PHONY : main3.o

# target to build an object file
main3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/main3.cpp.o
.PHONY : main3.cpp.o

main3.i: main3.cpp.i
.PHONY : main3.i

# target to preprocess a source file
main3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/main3.cpp.i
.PHONY : main3.cpp.i

main3.s: main3.cpp.s
.PHONY : main3.s

# target to generate assembly for a file
main3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Main.dir/build.make CMakeFiles/Main.dir/main3.cpp.s
.PHONY : main3.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Aero"
	@echo "... Core"
	@echo "... Forcegenerator"
	@echo "... LocusMathFunctions"
	@echo "... Main"
	@echo "... RigidBody"
	@echo "... RigidBodyDrawer"
	@echo "... World"
	@echo "... imgui"
	@echo "... implot"
	@echo "... rlImgui"
	@echo "... main3.o"
	@echo "... main3.i"
	@echo "... main3.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

